(in-package :gx-user)

(defun ub-default-uri2symbol-package-mapping-fun (uri)
  (declare (ignore uri))
  (find-package :|ub|))

(defun ub-default-uri2symbol-name-mapping-fun (uri)
  ;; This function is called only uri without fragment.
  (let ((host (net.uri:uri-host uri))
        (path (net.uri:uri-path uri)))
    (setq host (subseq host 4 (- (length host) 3)))
    (when path (setq path (subseq path 1)))
    (concatenate 'string host path)))

(setq *uri2symbol-name-mapping-fun* 'ub-default-uri2symbol-name-mapping-fun)
(setq *uri2symbol-package-mapping-fun* 'ub-default-uri2symbol-package-mapping-fun)

(let ((*default-pathname-defaults* (make-pathname :name cl:nil :type cl:nil :version cl:nil 
                                                  :defaults (load-time-value *load-pathname*))))
  (read-rdf-file #'addRdfXml "univ-bench.owl")
  )

(defun load-lubm10ver17 ()
  (let (;(*default-pathname-defaults* (make-pathname :name cl:nil :type cl:nil :version cl:nil 
        ;                                            :defaults (load-time-value *load-pathname*)))
        ;(*base-uri* (uri "http://www.lehigh.edu/%7Ezhp2/2004/0401/univ-bench.owl"))
	)
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-0.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-1.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-2.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-3.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-4.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-5.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-6.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-7.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-8.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-9.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-10.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-11.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-12.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-13.owl")
    (read-rdf-file #'addRdfXml "..\\..\\LUBM\\University\\University0-14.owl")
    ))

(defun load-lubm50ver17 ()
  (let ((*default-pathname-defaults* (make-pathname :name cl:nil :type cl:nil :version cl:nil 
                                                    :defaults (load-time-value *load-pathname*)))
        (*base-uri* (uri "http://www.lehigh.edu/%7Ezhp2/2004/0401/univ-bench.owl")))
    (read-rdf-file #'addRdfXml "LUBM50\\University0-0.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-1.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-2.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-3.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-4.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-5.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-6.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-7.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-8.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-9.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-10.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-11.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-12.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-13.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University0-14.owl")
    ;;
    (read-rdf-file #'addRdfXml "LUBM50\\University1-0.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-1.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-2.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-3.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-4.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-5.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-6.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-7.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-8.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-9.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-10.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-11.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-12.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-13.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-14.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-15.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-16.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-17.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University1-18.owl")
    ;;
    (read-rdf-file #'addRdfXml "LUBM50\\University2-0.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-1.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-2.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-3.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-4.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-5.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-6.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-7.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-8.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-9.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-10.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-11.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-12.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-13.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-14.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University2-15.owl")
    ;;
    (read-rdf-file #'addRdfXml "LUBM50\\University3-0.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-1.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-2.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-3.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-4.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-5.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-6.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-7.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-8.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-9.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-10.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-11.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-12.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-13.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-14.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-15.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-16.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-17.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-18.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-19.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University3-20.owl")
    ;;
    (read-rdf-file #'addRdfXml "LUBM50\\University4-0.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-1.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-2.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-3.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-4.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-5.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-6.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-7.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-8.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-9.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-10.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-11.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-12.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-13.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-14.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-15.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-16.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-17.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-18.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-19.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-20.owl")
    (read-rdf-file #'addRdfXml "LUBM50\\University4-21.owl")
    ))

(eval-when (:execute :load-toplevel)
  (format t "~%;Please cklick '>' and type in followings.~%;> (in-package gx-user)~%;> (time
 (let ((*error-output* cl:nil)
       (*autoepistemic-local-closed-world* cl:nil))
(load-lubm10ver17)))~%;> (query)")
  )
