(in-package gx)
(eq (symbol-value '|rdfs|:|Class|) (find-class '|rdfs|:|Class|))
(eq (symbol-value '|rdfs|:|Resource|) (find-class '|rdfs|:|Resource|))
(eq (symbol-value '|rdf|:|Property|) (find-class '|rdf|:|Property|))
(cl:typep (find-class 'meta-galaxy) (find-class 'cl:standard-class))
(cl:typep (find-class 'galaxy) (find-class 'meta-galaxy))
(cl:typep (find-class 'metaRDFSclass) (find-class 'cl:standard-class))
(cl:typep (find-class 'RDFSclass) (find-class 'metaRDFSclass))
(cl:typep (find-class '|rdfs|:|Class|) (find-class 'RDFSclass))
(cl:typep (find-class '|rdfs|:|Resource|) (find-class '|rdfs|:|Class|))
(cl:typep (find-class '|rdf|:|Property|) (find-class '|rdfs|:|Class|))
;
(cl:subtypep (find-class 'galaxy) (find-class 'cl:standard-object))
(cl:subtypep (find-class 'meta-galaxy) (find-class 'cl:standard-class))
(cl:subtypep (find-class 'metaRDFSclass) (find-class 'cl:standard-class))
(cl:subtypep (find-class 'RDFSclass) (find-class 'meta-galaxy))
(cl:subtypep (find-class '|rdfs|:|Class|) (find-class 'meta-galaxy))
(cl:subtypep (find-class '|rdfs|:|Resource|) (find-class 'galaxy))
(cl:subtypep (find-class '|rdfs|:|Class|) (find-class '|rdfs|:|Resource|))
(cl:subtypep (find-class '|rdf|:|Property|) (find-class '|rdfs|:|Resource|))

(defpackage vin)
(defResource vin::Zinfandel (|rdfs|:|subClassOf| vin::Wine))
(defIndividual vin::ElyseZinfandel (|rdf|:|type| vin::Zinfandel)
  (vin::hasColor 123)
  (vin::hasMaker vin::Elyse))
(defProperty vin:hasMaker (|rdfs|:|range| vin::Winery))
(defProperty vin:hasColor (|rdfs|:|range| vin::Color))

(in-package gx)
(defpackage vin)
(defIndividual vin::ElyseZinfandel (|rdf|:|type| vin::Zinfandel)
  (vin::hasColor vin::Red)
  (vin::hasMaker vin::Elyse))
(defProperty vin::hasWineDescriptor (|rdfs|:|domain| vin::Wine))
(defProperty vin::hasColor
    (|rdfs|:|subPropertyOf| vin:hasWineDescriptor))

(defResource vin::Zinfandel (|rdfs|:|subClassOf| vin::Wine))
